### ISSUE TITLE
Script always exits after copying compatdata

### ISSUE THREAD

**Issue by zimsneexh** [KaffeinatedKat/Linux-Nitrox-Launcher#1]
Hey,
I tried running your script to launch the game but it simply exits after copying compatdata.
Removing the OR "block" allows it to run just fine and it works after that.

Could be that it always executes the &&?

**Comment by KaffeinatedKat** [comment]
Yes it seems the && operator executes regardless of the completion of the || operator. I have removed the OR block as you instructed and it seems to work properly now
